name: CI
on:
  push:
    branches:
      - master
jobs:
  review:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/professor-rvenson/backend-n1-validate
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Validate
        run: validate
        env:
          STUDENT_ID: ${{ vars.STUDENT_ID }}
          STUDENT_NAME: ${{ vars.STUDENT_NAME }}
